= DocOps.io AsciiDoctorJ Architecture Decision Record(ARD)
Steve D Roach
:email: sroachst@gmail.com
:stylesdir: styles
:stylesheet: asciidoctor.css
:toc: left
:sectnums:
:title-page:
:source-highlighter: highlightjs
:nofooter:
:imagesdir: images
:data-uri:

== What is it?

An Architectural Decision (AD) is a software design choice that addresses a functional or non-functional requirement that is architecturally significant.
https://adr.github.io[ADR]

== How to use?

[source,asciidoc]
-----
[adr,test2,border=false] <1> <2> <3>
----
include::123.adr[] <4>
----
-----

<1> adr - name of the extenstion
<2> test2 - name of the generated file
<3> border -> use shadowed border or not
<4> file that contains the adr format


=== ADR Format

* Using colons as separators for the file layout.
....
Title:Arch decision Title <1>
Date: November 24th, 2010 <2>
Status: Proposed <3>
Context: Setting the context here <4>
Consequences: What are the consequences of the decision <5>
Participants: Architect,Engineer <6>
....

<1> Title for the record
<2> Date for the record
<3> Status can be 1 of (Proposed, Accepted, Superseded, Deprecated, Rejected)
<4> Context
<5> Consequences
<6> Participants (optional)

=== First Example

- Contents of 123.adr


....
include::123.adr[]
....


=== Resulting ADR

[adr,test3,border=true, newWin=true]
----
include::123.adr[]
----

==== New Window Test

[adr,test4,border=true, newWin=false]
----
include::456.adr[]
----

.Source for Non New Window

[source,asciidoc]
-----
[adr,test4,border=true, newWin=false]
----
include::456.adr[] <1>
----
-----

<1> Included adr file

== ADR Summary Example

[adrsummary]
----
123.adr
http://127.0.0.1:8000/src/main/docs/456.adr
http://127.0.0.1:8000/src/main/docs/123.adr
----

=== ADR Summary Source

[WARNING]
====
Only adr files can be processes. Recommend using adr files and include as you can version control this file.
====

[source,asciidoc]
-----
[adrsummary]
----
123.adr <1>
http://127.0.0.1:8000/src/main/docs/456.adr <2>
http://127.0.0.1:8000/src/main/docs/123.adr
----
-----

<1> Relative path to current document
<2> Full URL to adr